name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  os: ubuntu-latest
  node-version: 16

jobs:
  test:
    name: Test
    runs-on: ${{ env.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - id: find-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.find-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn test
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build

  release:
    name: Release
    runs-on: ${{ env.os }}
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: Release
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
